name: Deploy to ACR

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch. Change as needed.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Log in to ACR
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Docker Login
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.REGISTRY_URL }}
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.5.0
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.IMAGE_NAME }}
